# .github/workflows/deploy.yaml ── PeerPay (refactored)
name: Deploy
on:
  push:
    branches:
      - master
      - production

permissions:          # required for Workload-Identity Federation
  contents: read
  id-token: write

env:                  # ── static values
  GCR_HOST:       us.gcr.io
  GCP_PROJECT_ID: babbage-private
  IMAGE_NAME:     peerpay-react

jobs:
  build-and-deploy:
    name: Build-&-Deploy to Cloud Run
    runs-on: ubuntu-latest

    env:            # ── values that depend on the branch
      CURRENT_BRANCH: ${{ github.ref_name == 'production' && 'production' || 'master' }}

    steps:
    # ──────── 1. Sources & toolchain ────────────────────────────────────────
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    # Optional early-fail build of the React bundle
    - name: Install deps & build bundle
      run: |
        npm ci
        CI=true npm run build

    # ──────── 2. Authenticate for docker push ──────────────────────────────
    - name: Auth (push to Container Registry)
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.DOCKER_REGISTRY_PUSH_KEY }}

    # ──────── 3. Build & push image (RafikFarhad) ──────────────────────────
    - name: Build and push image
      id: push-image
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.DOCKER_REGISTRY_PUSH_KEY }}
        registry:    ${{ env.GCR_HOST }}
        project_id:  ${{ env.GCP_PROJECT_ID }}
        image_name:  ${{ env.IMAGE_NAME }}
        image_tag:   latest,${{ env.CURRENT_BRANCH }}-${{ github.sha }}

    # expose the per-commit tag for later steps
    - name: Set image URI output
      run: |
        echo "IMAGE_URI=${{ env.GCR_HOST }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.CURRENT_BRANCH }}-${{ github.sha }}" >> "$GITHUB_OUTPUT"

    # ──────── 4. Authenticate for deployment ───────────────────────────────
    - name: Auth (deploy to Cloud Run)
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_DEPLOY_CREDS }}

    # ──────── 5. Deploy to Cloud Run ────────────────────────────────────────
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.IMAGE_NAME }}-${{ env.CURRENT_BRANCH }}
        image:   ${{ steps.set-image-uri.outputs.IMAGE_URI }}
        region:  us-central1
        timeout: 3540

    # ──────── 6. Post-deploy tweaks (optional) ─────────────────────────────
    - name: Set min instances & enable CPU boost
      run: |
        SERVICE_NAME=${{ env.IMAGE_NAME }}-${{ env.CURRENT_BRANCH }}
        gcloud run services update "$SERVICE_NAME" \
          --region=us-central1 \
          --no-use-http2
